services:
  linux1:
    build: .
    image: linux-test
    command: tail -f /dev/null
    tmpfs:
      - /disco-temporal
    volumes:
      - compartido:/disco-constante
  linux2:
    build: .
    image: linux-test
    command: tail -f /dev/null
    tmpfs:
      - /disco-temporal
    volumes:
      - compartido:/disco-constante
volumes:
  compartido:
